### ISSUE TITLE
Source Files do not match the compiled binary

### ISSUE THREAD

**Issue by jmg5150** [SmartArduino/WiFiMCU-STUDIO#1]
The compiled binary checked in to the repo has buttons on the "Firmware" tab, however this functionality is missing from the source files. Please check in the latest version of the source files so that myself & other developers can work on making improvements to the latest available code.

**Comment by SmartArduino** [comment]
I had noticed this bug,  I will upload a new version later today.

**Comment by jmg5150** [comment]
Thanks so much! I pulled the updates you checked in, looks good! :-)
