### ISSUE TITLE
Seperate Firmware Loader

### ISSUE THREAD

**Issue by eliabieri** [SmartArduino/WiFiMCU-STUDIO#2]
Since the Studio does not support mac, it would be cool if you released the bare firmware loader.
I hope the firmware loader would be easy to patch for mac OS X

**Comment by SmartArduino** [comment]
Hi, Eliabieri,
The firmware uploading is based on Y modem transmission protocol, You can check the bootloader source code in WiFiMCU project. Any serial port interface such as secureCRT would support uploading function.
