### ISSUE TITLE
WiFiMCU-STUDIO v2.0 and v2.1 file upload fails. File upload works with version 1.04

### ISSUE THREAD

**Issue by Seagoon** [SmartArduino/WiFiMCU-STUDIO#3]
When trying to upload a file init.lua to WifiMCU (running WiFiMCU_Bootloader.V1.1.bin and WiFiMCU_Firmware_Float.v0.9.8._20151216.bin) I get the following error. I reboot the MCU and try again and get the same error. 

> Start upload file: 'init.lua'
> .
>  Error happened, stop download!
> mcu.reboot()

  ;   .  . .___ .  . __ .  .      ,--.
 ["]  |  |o[__ o|\/|/  `|  | ,<-|**oo|
/[_]\ |/|||   ||  |\**.|**| /  |//  |
 ] [                            /o|**| [ Ver. 0.9.8_alpha WiFiMCU Team @2015 ]

lua: init.lua:1: unexpected symbol

> Start upload file: 'init.lua'
> .
>  Error happened, stop download!
> =file.state()
> init.lua    0

The older WiFiMCU studio version 1.0.4 file upload works.

> =mcu.ver()
> WiFiMCU 0.9.8   build 20151216
> 
> Start upload file: 'init.lua'..
> ..
> -->Upload file: 'init.lua' successful<--

OS: Windows 7.1 64Bit. 
Screenshot:

![capture](https://cloud.githubusercontent.com/assets/13390225/12107284/a90edfa2-b3a3-11e5-9985-b175b214c027.PNG)

**Comment by SmartArduino** [comment]
Would you please post the init.lua file?
Or change the encode of the file in a notpad++ and try again

**Comment by Seagoon** [comment]
Hi,

The contents connect to my wifi. It is simply this:

cfg={ssid='mySSID',pwd='mypassword'};wifi.startsta(cfg);cfg=nil;

If I upload that file with WiFiMCU Studio v1.0.4 it uploads correctly and on reboot the WiFiMCU connects to my WiFi AP.

Thanks,

p.s. I opened it in notepad++, and re-saved it and I still get the same error.

**Comment by SmartArduino** [comment]
I just try this, and failed too.
It's a soft bug in WiFiMCU Studio2.0 or 2.1. I think that is because of the lua file is only one line. If you change it to two or more lines, it'll be ok.
Thanks for your post.

**Comment by Seagoon** [comment]
Hi,

That worked, thanks!

**Comment by Alex-Stanfield** [comment]
I'm having the same problem! However my file has several lines and I can't upload even with version 1.04

Any clues?

I'm desperate to use my WiFiMCU and can't  ;-)

Thanks in advance
Alex
